
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.VBox vbox10;
	
	private global::Gtk.HBox hbox13;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Entry dev;
	
	private global::Gtk.Button button51;
	
	private global::Gtk.Image ready;
	
	private global::Gtk.Frame frame2;
	
	private global::Gtk.Alignment GtkAlignment24;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox12;
	
	private global::Gtk.Fixed fixed32;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Button tvrad;
	
	private global::Gtk.Button avmode;
	
	private global::Gtk.Button power;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.Button input;
	
	private global::Gtk.Button energysaving;
	
	private global::Gtk.Fixed fixed33;
	
	private global::Gtk.HSeparator hseparator3;
	
	private global::Gtk.Table table3;
	
	private global::Gtk.Fixed fixed10;
	
	private global::Gtk.Fixed fixed11;
	
	private global::Gtk.Fixed fixed12;
	
	private global::Gtk.Fixed fixed13;
	
	private global::Gtk.Fixed fixed14;
	
	private global::Gtk.Fixed fixed9;
	
	private global::Gtk.Button n1;
	
	private global::Gtk.Button n2;
	
	private global::Gtk.Button n3;
	
	private global::Gtk.Button n4;
	
	private global::Gtk.Button n5;
	
	private global::Gtk.Button n6;
	
	private global::Gtk.Button n7;
	
	private global::Gtk.Button n8;
	
	private global::Gtk.Button n9;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.Button blue;
	
	private global::Gtk.Button epg;
	
	private global::Gtk.Fixed fixed28;
	
	private global::Gtk.Fixed fixed31;
	
	private global::Gtk.Fixed fixed34;
	
	private global::Gtk.Fixed fixed35;
	
	private global::Gtk.Fixed fixed6;
	
	private global::Gtk.Fixed fixed7;
	
	private global::Gtk.Button green;
	
	private global::Gtk.Button info;
	
	private global::Gtk.Button markfav;
	
	private global::Gtk.Button qmenu;
	
	private global::Gtk.Button red;
	
	private global::Gtk.Button simplink;
	
	private global::Gtk.Button subtitle;
	
	private global::Gtk.Button text;
	
	private global::Gtk.Button topt;
	
	private global::Gtk.Button yellow;
	
	private global::Gtk.HBox hbox18;
	
	private global::Gtk.Fixed fixed36;
	
	private global::Gtk.Button bwd;
	
	private global::Gtk.Button fwd;
	
	private global::Gtk.Fixed fixed37;
	
	private global::Gtk.HBox hbox17;
	
	private global::Gtk.Fixed fixed5;
	
	private global::Gtk.Button play;
	
	private global::Gtk.Button pause;
	
	private global::Gtk.Button stop;
	
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.HSeparator hseparator4;
	
	private global::Gtk.HBox hbox11;
	
	private global::Gtk.Button menu;
	
	private global::Gtk.Button ratio;
	
	private global::Gtk.Button exit;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Button down;
	
	private global::Gtk.Fixed fixed20;
	
	private global::Gtk.Fixed fixed21;
	
	private global::Gtk.Fixed fixed22;
	
	private global::Gtk.Fixed fixed23;
	
	private global::Gtk.Fixed fixed24;
	
	private global::Gtk.Fixed fixed25;
	
	private global::Gtk.Fixed fixed26;
	
	private global::Gtk.Fixed fixed27;
	
	private global::Gtk.Fixed fixed29;
	
	private global::Gtk.Fixed fixed30;
	
	private global::Gtk.Button left;
	
	private global::Gtk.Button ok;
	
	private global::Gtk.Button right;
	
	private global::Gtk.Button up;
	
	private global::Gtk.HSeparator hseparator2;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.Fixed fixed17;
	
	private global::Gtk.VBox vbox7;
	
	private global::Gtk.Button vup;
	
	private global::Gtk.Image image31;
	
	private global::Gtk.Button vdown;
	
	private global::Gtk.VBox vbox8;
	
	private global::Gtk.Fixed fixed18;
	
	private global::Gtk.Button mute;
	
	private global::Gtk.Fixed fixed19;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.Button pup;
	
	private global::Gtk.Image image37;
	
	private global::Gtk.Button pdown;
	
	private global::Gtk.Fixed fixed16;
	
	private global::Gtk.HSeparator hseparator5;
	
	private global::Gtk.HBox hbox10;
	
	private global::Gtk.Fixed fixed8;
	
	private global::Gtk.Button list;
	
	private global::Gtk.Button n;
	
	private global::Gtk.Button qview;
	
	private global::Gtk.Fixed fixed15;
	
	private global::Gtk.Label GtkLabel46;
	
	private global::Gtk.VSeparator vseparator1;
	
	private global::Gtk.VBox vbox9;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Label tvstate;
	
	private global::Gtk.Image tvimage;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label aspect;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.ComboBox aspectselect;
	
	private global::Gtk.Button aspectsend;
	
	private global::Gtk.HSeparator hseparator6;
	
	private global::Gtk.VBox vbox11;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label volumeview;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.SpinButton volumeselect;
	
	private global::Gtk.Button volumesend;
	
	private global::Gtk.HScale volumescroll;
	
	private global::Gtk.HSeparator hseparator7;
	
	private global::Gtk.VBox vbox12;
	
	private global::Gtk.HBox hbox14;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Label programview;
	
	private global::Gtk.HBox hbox8;
	
	private global::Gtk.Fixed fixed3;
	
	private global::Gtk.SpinButton programselect;
	
	private global::Gtk.Button programbut;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.HSeparator hseparator8;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.HBox hbox15;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Label inputview;
	
	private global::Gtk.HBox hbox16;
	
	private global::Gtk.Fixed fixed4;
	
	private global::Gtk.ComboBox inputselect;
	
	private global::Gtk.Button inputsend;
	
	private global::Gtk.Button autoconf;
	
	private global::Gtk.HSeparator hseparator9;
	
	private global::Gtk.VBox vbox13;
	
	private global::Gtk.Button quit;
	
	private global::Gtk.Button button3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Ovládání TV");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		this.hbox7.BorderWidth = ((uint)(11));
		// Container child hbox7.Gtk.Box+BoxChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Zařízení:</b>");
		this.label3.UseMarkup = true;
		this.hbox13.Add (this.label3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label3]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.dev = new global::Gtk.Entry ();
		this.dev.CanFocus = true;
		this.dev.Name = "dev";
		this.dev.IsEditable = true;
		this.dev.InvisibleChar = '•';
		this.hbox13.Add (this.dev);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.dev]));
		w2.Position = 1;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button51 = new global::Gtk.Button ();
		this.button51.CanFocus = true;
		this.button51.Name = "button51";
		this.button51.UseUnderline = true;
		this.button51.Label = global::Mono.Unix.Catalog.GetString ("Init");
		global::Gtk.Image w3 = new global::Gtk.Image ();
		w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Button);
		this.button51.Image = w3;
		this.hbox13.Add (this.button51);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.button51]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.ready = new global::Gtk.Image ();
		this.ready.Name = "ready";
		this.ready.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-disconnect", global::Gtk.IconSize.Button);
		this.hbox13.Add (this.ready);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.ready]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		this.vbox10.Add (this.hbox13);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox13]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment24 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment24.Name = "GtkAlignment24";
		this.GtkAlignment24.LeftPadding = ((uint)(12));
		// Container child GtkAlignment24.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		this.vbox2.BorderWidth = ((uint)(6));
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.fixed32 = new global::Gtk.Fixed ();
		this.fixed32.Name = "fixed32";
		this.fixed32.HasWindow = false;
		this.hbox12.Add (this.fixed32);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.fixed32]));
		w7.Position = 0;
		// Container child hbox12.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.tvrad = new global::Gtk.Button ();
		this.tvrad.WidthRequest = 80;
		this.tvrad.CanFocus = true;
		this.tvrad.Name = "tvrad";
		this.tvrad.UseUnderline = true;
		this.tvrad.Label = global::Mono.Unix.Catalog.GetString ("TV/Rad");
		global::Gtk.Image w8 = new global::Gtk.Image ();
		w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_playlist", global::Gtk.IconSize.Button);
		this.tvrad.Image = w8;
		this.vbox3.Add (this.tvrad);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.tvrad]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.avmode = new global::Gtk.Button ();
		this.avmode.WidthRequest = 80;
		this.avmode.CanFocus = true;
		this.avmode.Name = "avmode";
		this.avmode.UseUnderline = true;
		this.avmode.Label = global::Mono.Unix.Catalog.GetString ("AV Mód");
		global::Gtk.Image w10 = new global::Gtk.Image ();
		w10.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_edit", global::Gtk.IconSize.Button);
		this.avmode.Image = w10;
		this.vbox3.Add (this.avmode);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.avmode]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.hbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.power = new global::Gtk.Button ();
		this.power.CanFocus = true;
		this.power.Name = "power";
		this.power.UseUnderline = true;
		global::Gtk.Image w13 = new global::Gtk.Image ();
		w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_exit", global::Gtk.IconSize.Dialog);
		this.power.Image = w13;
		this.hbox1.Add (this.power);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.power]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.input = new global::Gtk.Button ();
		this.input.WidthRequest = 80;
		this.input.CanFocus = true;
		this.input.Name = "input";
		this.input.UseUnderline = true;
		this.input.Label = global::Mono.Unix.Catalog.GetString ("Vstup");
		global::Gtk.Image w15 = new global::Gtk.Image ();
		w15.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-select-color", global::Gtk.IconSize.Button);
		this.input.Image = w15;
		this.vbox4.Add (this.input);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.input]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.energysaving = new global::Gtk.Button ();
		this.energysaving.WidthRequest = 80;
		this.energysaving.CanFocus = true;
		this.energysaving.Name = "energysaving";
		this.energysaving.UseUnderline = true;
		this.energysaving.Label = global::Mono.Unix.Catalog.GetString ("Eko");
		global::Gtk.Image w17 = new global::Gtk.Image ();
		w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_weather-sunny", global::Gtk.IconSize.Button);
		this.energysaving.Image = w17;
		this.vbox4.Add (this.energysaving);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.energysaving]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.hbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.hbox12.Add (this.hbox1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.hbox1]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.fixed33 = new global::Gtk.Fixed ();
		this.fixed33.Name = "fixed33";
		this.fixed33.HasWindow = false;
		this.hbox12.Add (this.fixed33);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.fixed33]));
		w21.Position = 2;
		this.vbox2.Add (this.hbox12);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox12]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.Name = "hseparator3";
		this.vbox2.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator3]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table3 = new global::Gtk.Table (((uint)(3)), ((uint)(5)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(3));
		this.table3.ColumnSpacing = ((uint)(3));
		// Container child table3.Gtk.Table+TableChild
		this.fixed10 = new global::Gtk.Fixed ();
		this.fixed10.Name = "fixed10";
		this.fixed10.HasWindow = false;
		this.table3.Add (this.fixed10);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed10]));
		w24.LeftAttach = ((uint)(4));
		w24.RightAttach = ((uint)(5));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.fixed11 = new global::Gtk.Fixed ();
		this.fixed11.Name = "fixed11";
		this.fixed11.HasWindow = false;
		this.table3.Add (this.fixed11);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed11]));
		w25.TopAttach = ((uint)(1));
		w25.BottomAttach = ((uint)(2));
		w25.LeftAttach = ((uint)(4));
		w25.RightAttach = ((uint)(5));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.fixed12 = new global::Gtk.Fixed ();
		this.fixed12.Name = "fixed12";
		this.fixed12.HasWindow = false;
		this.table3.Add (this.fixed12);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed12]));
		w26.TopAttach = ((uint)(2));
		w26.BottomAttach = ((uint)(3));
		w26.LeftAttach = ((uint)(4));
		w26.RightAttach = ((uint)(5));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.fixed13 = new global::Gtk.Fixed ();
		this.fixed13.Name = "fixed13";
		this.fixed13.HasWindow = false;
		this.table3.Add (this.fixed13);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed13]));
		w27.TopAttach = ((uint)(1));
		w27.BottomAttach = ((uint)(2));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.fixed14 = new global::Gtk.Fixed ();
		this.fixed14.Name = "fixed14";
		this.fixed14.HasWindow = false;
		this.table3.Add (this.fixed14);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed14]));
		w28.TopAttach = ((uint)(2));
		w28.BottomAttach = ((uint)(3));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.fixed9 = new global::Gtk.Fixed ();
		this.fixed9.Name = "fixed9";
		this.fixed9.HasWindow = false;
		this.table3.Add (this.fixed9);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed9]));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.n1 = new global::Gtk.Button ();
		this.n1.WidthRequest = 30;
		this.n1.HeightRequest = 30;
		this.n1.CanFocus = true;
		this.n1.Name = "n1";
		this.n1.UseUnderline = true;
		this.n1.Label = global::Mono.Unix.Catalog.GetString ("1");
		this.table3.Add (this.n1);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table3 [this.n1]));
		w30.LeftAttach = ((uint)(1));
		w30.RightAttach = ((uint)(2));
		w30.XOptions = ((global::Gtk.AttachOptions)(4));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.n2 = new global::Gtk.Button ();
		this.n2.WidthRequest = 30;
		this.n2.HeightRequest = 30;
		this.n2.CanFocus = true;
		this.n2.Name = "n2";
		this.n2.UseUnderline = true;
		this.n2.Label = global::Mono.Unix.Catalog.GetString ("2");
		this.table3.Add (this.n2);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table3 [this.n2]));
		w31.LeftAttach = ((uint)(2));
		w31.RightAttach = ((uint)(3));
		w31.XOptions = ((global::Gtk.AttachOptions)(4));
		w31.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.n3 = new global::Gtk.Button ();
		this.n3.WidthRequest = 30;
		this.n3.HeightRequest = 30;
		this.n3.CanFocus = true;
		this.n3.Name = "n3";
		this.n3.UseUnderline = true;
		this.n3.Label = global::Mono.Unix.Catalog.GetString ("3");
		this.table3.Add (this.n3);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table3 [this.n3]));
		w32.LeftAttach = ((uint)(3));
		w32.RightAttach = ((uint)(4));
		w32.XOptions = ((global::Gtk.AttachOptions)(4));
		w32.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.n4 = new global::Gtk.Button ();
		this.n4.WidthRequest = 30;
		this.n4.HeightRequest = 30;
		this.n4.CanFocus = true;
		this.n4.Name = "n4";
		this.n4.UseUnderline = true;
		this.n4.Label = global::Mono.Unix.Catalog.GetString ("4");
		this.table3.Add (this.n4);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table3 [this.n4]));
		w33.TopAttach = ((uint)(1));
		w33.BottomAttach = ((uint)(2));
		w33.LeftAttach = ((uint)(1));
		w33.RightAttach = ((uint)(2));
		w33.XOptions = ((global::Gtk.AttachOptions)(4));
		w33.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.n5 = new global::Gtk.Button ();
		this.n5.WidthRequest = 30;
		this.n5.HeightRequest = 30;
		this.n5.CanFocus = true;
		this.n5.Name = "n5";
		this.n5.UseUnderline = true;
		this.n5.Label = global::Mono.Unix.Catalog.GetString ("5");
		this.table3.Add (this.n5);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table3 [this.n5]));
		w34.TopAttach = ((uint)(1));
		w34.BottomAttach = ((uint)(2));
		w34.LeftAttach = ((uint)(2));
		w34.RightAttach = ((uint)(3));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.n6 = new global::Gtk.Button ();
		this.n6.WidthRequest = 30;
		this.n6.HeightRequest = 30;
		this.n6.CanFocus = true;
		this.n6.Name = "n6";
		this.n6.UseUnderline = true;
		this.n6.Label = global::Mono.Unix.Catalog.GetString ("6");
		this.table3.Add (this.n6);
		global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table3 [this.n6]));
		w35.TopAttach = ((uint)(1));
		w35.BottomAttach = ((uint)(2));
		w35.LeftAttach = ((uint)(3));
		w35.RightAttach = ((uint)(4));
		w35.XOptions = ((global::Gtk.AttachOptions)(4));
		w35.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.n7 = new global::Gtk.Button ();
		this.n7.WidthRequest = 30;
		this.n7.HeightRequest = 30;
		this.n7.CanFocus = true;
		this.n7.Name = "n7";
		this.n7.UseUnderline = true;
		this.n7.Label = global::Mono.Unix.Catalog.GetString ("7");
		this.table3.Add (this.n7);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table3 [this.n7]));
		w36.TopAttach = ((uint)(2));
		w36.BottomAttach = ((uint)(3));
		w36.LeftAttach = ((uint)(1));
		w36.RightAttach = ((uint)(2));
		w36.XOptions = ((global::Gtk.AttachOptions)(4));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.n8 = new global::Gtk.Button ();
		this.n8.WidthRequest = 30;
		this.n8.HeightRequest = 30;
		this.n8.CanFocus = true;
		this.n8.Name = "n8";
		this.n8.UseUnderline = true;
		this.n8.Label = global::Mono.Unix.Catalog.GetString ("8");
		this.table3.Add (this.n8);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table3 [this.n8]));
		w37.TopAttach = ((uint)(2));
		w37.BottomAttach = ((uint)(3));
		w37.LeftAttach = ((uint)(2));
		w37.RightAttach = ((uint)(3));
		w37.XOptions = ((global::Gtk.AttachOptions)(4));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.n9 = new global::Gtk.Button ();
		this.n9.WidthRequest = 30;
		this.n9.HeightRequest = 30;
		this.n9.CanFocus = true;
		this.n9.Name = "n9";
		this.n9.UseUnderline = true;
		this.n9.Label = global::Mono.Unix.Catalog.GetString ("9");
		this.table3.Add (this.n9);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table3 [this.n9]));
		w38.TopAttach = ((uint)(2));
		w38.BottomAttach = ((uint)(3));
		w38.LeftAttach = ((uint)(3));
		w38.RightAttach = ((uint)(4));
		w38.XOptions = ((global::Gtk.AttachOptions)(4));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox2.Add (this.table3);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table3]));
		w39.Position = 2;
		w39.Expand = false;
		w39.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(6)), false);
		this.table2.Name = "table2";
		// Container child table2.Gtk.Table+TableChild
		this.blue = new global::Gtk.Button ();
		this.blue.WidthRequest = 68;
		this.blue.CanFocus = true;
		this.blue.Name = "blue";
		this.blue.UseUnderline = true;
		global::Gtk.Image w40 = new global::Gtk.Image ();
		w40.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("TVControl.blue.png");
		this.blue.Image = w40;
		this.table2.Add (this.blue);
		global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table2 [this.blue]));
		w41.LeftAttach = ((uint)(4));
		w41.RightAttach = ((uint)(5));
		w41.XOptions = ((global::Gtk.AttachOptions)(4));
		w41.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.epg = new global::Gtk.Button ();
		this.epg.WidthRequest = 68;
		this.epg.CanFocus = true;
		this.epg.Name = "epg";
		this.epg.UseUnderline = true;
		this.epg.Label = global::Mono.Unix.Catalog.GetString ("EPG");
		this.table2.Add (this.epg);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table2 [this.epg]));
		w42.TopAttach = ((uint)(2));
		w42.BottomAttach = ((uint)(3));
		w42.LeftAttach = ((uint)(3));
		w42.RightAttach = ((uint)(4));
		w42.XOptions = ((global::Gtk.AttachOptions)(4));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.fixed28 = new global::Gtk.Fixed ();
		this.fixed28.Name = "fixed28";
		this.fixed28.HasWindow = false;
		this.table2.Add (this.fixed28);
		global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed28]));
		w43.TopAttach = ((uint)(1));
		w43.BottomAttach = ((uint)(2));
		w43.LeftAttach = ((uint)(5));
		w43.RightAttach = ((uint)(6));
		w43.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.fixed31 = new global::Gtk.Fixed ();
		this.fixed31.Name = "fixed31";
		this.fixed31.HasWindow = false;
		this.table2.Add (this.fixed31);
		global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed31]));
		w44.TopAttach = ((uint)(2));
		w44.BottomAttach = ((uint)(3));
		w44.LeftAttach = ((uint)(5));
		w44.RightAttach = ((uint)(6));
		w44.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.fixed34 = new global::Gtk.Fixed ();
		this.fixed34.Name = "fixed34";
		this.fixed34.HasWindow = false;
		this.table2.Add (this.fixed34);
		global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed34]));
		w45.TopAttach = ((uint)(1));
		w45.BottomAttach = ((uint)(2));
		w45.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.fixed35 = new global::Gtk.Fixed ();
		this.fixed35.Name = "fixed35";
		this.fixed35.HasWindow = false;
		this.table2.Add (this.fixed35);
		global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed35]));
		w46.TopAttach = ((uint)(2));
		w46.BottomAttach = ((uint)(3));
		w46.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.fixed6 = new global::Gtk.Fixed ();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		this.table2.Add (this.fixed6);
		global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed6]));
		w47.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.fixed7 = new global::Gtk.Fixed ();
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		this.table2.Add (this.fixed7);
		global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table2 [this.fixed7]));
		w48.LeftAttach = ((uint)(5));
		w48.RightAttach = ((uint)(6));
		w48.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.green = new global::Gtk.Button ();
		this.green.WidthRequest = 68;
		this.green.CanFocus = true;
		this.green.Name = "green";
		this.green.UseUnderline = true;
		global::Gtk.Image w49 = new global::Gtk.Image ();
		w49.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("TVControl.green.png");
		this.green.Image = w49;
		this.table2.Add (this.green);
		global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table2 [this.green]));
		w50.LeftAttach = ((uint)(2));
		w50.RightAttach = ((uint)(3));
		w50.XOptions = ((global::Gtk.AttachOptions)(4));
		w50.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.info = new global::Gtk.Button ();
		this.info.WidthRequest = 68;
		this.info.CanFocus = true;
		this.info.Name = "info";
		this.info.UseUnderline = true;
		this.info.Label = global::Mono.Unix.Catalog.GetString ("Info");
		global::Gtk.Image w51 = new global::Gtk.Image ();
		w51.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-info", global::Gtk.IconSize.Button);
		this.info.Image = w51;
		this.table2.Add (this.info);
		global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table2 [this.info]));
		w52.TopAttach = ((uint)(2));
		w52.BottomAttach = ((uint)(3));
		w52.LeftAttach = ((uint)(2));
		w52.RightAttach = ((uint)(3));
		w52.XOptions = ((global::Gtk.AttachOptions)(4));
		w52.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.markfav = new global::Gtk.Button ();
		this.markfav.WidthRequest = 68;
		this.markfav.CanFocus = true;
		this.markfav.Name = "markfav";
		this.markfav.UseUnderline = true;
		this.markfav.Label = global::Mono.Unix.Catalog.GetString ("Oblíb.");
		global::Gtk.Image w53 = new global::Gtk.Image ();
		w53.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_add-bookmark", global::Gtk.IconSize.Button);
		this.markfav.Image = w53;
		this.table2.Add (this.markfav);
		global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table2 [this.markfav]));
		w54.TopAttach = ((uint)(2));
		w54.BottomAttach = ((uint)(3));
		w54.LeftAttach = ((uint)(4));
		w54.RightAttach = ((uint)(5));
		w54.XOptions = ((global::Gtk.AttachOptions)(4));
		w54.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.qmenu = new global::Gtk.Button ();
		this.qmenu.WidthRequest = 68;
		this.qmenu.CanFocus = true;
		this.qmenu.Name = "qmenu";
		this.qmenu.UseUnderline = true;
		this.qmenu.Label = global::Mono.Unix.Catalog.GetString ("Q.Menu");
		this.table2.Add (this.qmenu);
		global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table2 [this.qmenu]));
		w55.TopAttach = ((uint)(2));
		w55.BottomAttach = ((uint)(3));
		w55.LeftAttach = ((uint)(1));
		w55.RightAttach = ((uint)(2));
		w55.XOptions = ((global::Gtk.AttachOptions)(4));
		w55.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.red = new global::Gtk.Button ();
		this.red.WidthRequest = 68;
		this.red.CanFocus = true;
		this.red.Name = "red";
		this.red.UseUnderline = true;
		global::Gtk.Image w56 = new global::Gtk.Image ();
		w56.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("TVControl.red.png");
		this.red.Image = w56;
		this.table2.Add (this.red);
		global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table2 [this.red]));
		w57.LeftAttach = ((uint)(1));
		w57.RightAttach = ((uint)(2));
		w57.XOptions = ((global::Gtk.AttachOptions)(4));
		w57.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.simplink = new global::Gtk.Button ();
		this.simplink.WidthRequest = 68;
		this.simplink.CanFocus = true;
		this.simplink.Name = "simplink";
		this.simplink.UseUnderline = true;
		this.simplink.Label = global::Mono.Unix.Catalog.GetString ("SimpLink");
		this.table2.Add (this.simplink);
		global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table2 [this.simplink]));
		w58.TopAttach = ((uint)(1));
		w58.BottomAttach = ((uint)(2));
		w58.LeftAttach = ((uint)(4));
		w58.RightAttach = ((uint)(5));
		w58.XOptions = ((global::Gtk.AttachOptions)(4));
		w58.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.subtitle = new global::Gtk.Button ();
		this.subtitle.WidthRequest = 68;
		this.subtitle.CanFocus = true;
		this.subtitle.Name = "subtitle";
		this.subtitle.UseUnderline = true;
		this.subtitle.Label = global::Mono.Unix.Catalog.GetString ("Titulky");
		this.table2.Add (this.subtitle);
		global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table2 [this.subtitle]));
		w59.TopAttach = ((uint)(1));
		w59.BottomAttach = ((uint)(2));
		w59.LeftAttach = ((uint)(3));
		w59.RightAttach = ((uint)(4));
		w59.XOptions = ((global::Gtk.AttachOptions)(4));
		w59.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.text = new global::Gtk.Button ();
		this.text.WidthRequest = 68;
		this.text.CanFocus = true;
		this.text.Name = "text";
		this.text.UseUnderline = true;
		this.text.Label = global::Mono.Unix.Catalog.GetString ("Text");
		global::Gtk.Image w60 = new global::Gtk.Image ();
		w60.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-file", global::Gtk.IconSize.Button);
		this.text.Image = w60;
		this.table2.Add (this.text);
		global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table2 [this.text]));
		w61.TopAttach = ((uint)(1));
		w61.BottomAttach = ((uint)(2));
		w61.LeftAttach = ((uint)(1));
		w61.RightAttach = ((uint)(2));
		w61.XOptions = ((global::Gtk.AttachOptions)(4));
		w61.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.topt = new global::Gtk.Button ();
		this.topt.WidthRequest = 68;
		this.topt.CanFocus = true;
		this.topt.Name = "topt";
		this.topt.UseUnderline = true;
		this.topt.Label = global::Mono.Unix.Catalog.GetString ("T. Opt");
		this.table2.Add (this.topt);
		global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table2 [this.topt]));
		w62.TopAttach = ((uint)(1));
		w62.BottomAttach = ((uint)(2));
		w62.LeftAttach = ((uint)(2));
		w62.RightAttach = ((uint)(3));
		w62.XOptions = ((global::Gtk.AttachOptions)(4));
		w62.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.yellow = new global::Gtk.Button ();
		this.yellow.WidthRequest = 68;
		this.yellow.CanFocus = true;
		this.yellow.Name = "yellow";
		this.yellow.UseUnderline = true;
		global::Gtk.Image w63 = new global::Gtk.Image ();
		w63.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("TVControl.yellow.png");
		this.yellow.Image = w63;
		this.table2.Add (this.yellow);
		global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table2 [this.yellow]));
		w64.LeftAttach = ((uint)(3));
		w64.RightAttach = ((uint)(4));
		w64.XOptions = ((global::Gtk.AttachOptions)(4));
		w64.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox2.Add (this.table2);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table2]));
		w65.PackType = ((global::Gtk.PackType)(1));
		w65.Position = 3;
		w65.Expand = false;
		w65.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox18 = new global::Gtk.HBox ();
		this.hbox18.Name = "hbox18";
		this.hbox18.Spacing = 6;
		// Container child hbox18.Gtk.Box+BoxChild
		this.fixed36 = new global::Gtk.Fixed ();
		this.fixed36.Name = "fixed36";
		this.fixed36.HasWindow = false;
		this.hbox18.Add (this.fixed36);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.fixed36]));
		w66.Position = 0;
		// Container child hbox18.Gtk.Box+BoxChild
		this.bwd = new global::Gtk.Button ();
		this.bwd.WidthRequest = 90;
		this.bwd.CanFocus = true;
		this.bwd.Name = "bwd";
		this.bwd.UseUnderline = true;
		this.bwd.Label = global::Mono.Unix.Catalog.GetString ("Dozadu");
		global::Gtk.Image w67 = new global::Gtk.Image ();
		w67.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-rewind", global::Gtk.IconSize.Button);
		this.bwd.Image = w67;
		this.hbox18.Add (this.bwd);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.bwd]));
		w68.Position = 1;
		w68.Expand = false;
		w68.Fill = false;
		// Container child hbox18.Gtk.Box+BoxChild
		this.fwd = new global::Gtk.Button ();
		this.fwd.WidthRequest = 90;
		this.fwd.CanFocus = true;
		this.fwd.Name = "fwd";
		this.fwd.UseUnderline = true;
		this.fwd.Label = global::Mono.Unix.Catalog.GetString ("Dopředu");
		global::Gtk.Image w69 = new global::Gtk.Image ();
		w69.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-forward", global::Gtk.IconSize.Button);
		this.fwd.Image = w69;
		this.hbox18.Add (this.fwd);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.fwd]));
		w70.Position = 2;
		w70.Expand = false;
		w70.Fill = false;
		// Container child hbox18.Gtk.Box+BoxChild
		this.fixed37 = new global::Gtk.Fixed ();
		this.fixed37.Name = "fixed37";
		this.fixed37.HasWindow = false;
		this.hbox18.Add (this.fixed37);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.fixed37]));
		w71.Position = 3;
		this.vbox2.Add (this.hbox18);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox18]));
		w72.PackType = ((global::Gtk.PackType)(1));
		w72.Position = 4;
		w72.Expand = false;
		w72.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox17 = new global::Gtk.HBox ();
		this.hbox17.Name = "hbox17";
		this.hbox17.Spacing = 6;
		// Container child hbox17.Gtk.Box+BoxChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		this.hbox17.Add (this.fixed5);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.fixed5]));
		w73.Position = 0;
		// Container child hbox17.Gtk.Box+BoxChild
		this.play = new global::Gtk.Button ();
		this.play.WidthRequest = 80;
		this.play.CanFocus = true;
		this.play.Name = "play";
		this.play.UseUnderline = true;
		this.play.Label = global::Mono.Unix.Catalog.GetString ("Přehrát");
		global::Gtk.Image w74 = new global::Gtk.Image ();
		w74.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Button);
		this.play.Image = w74;
		this.hbox17.Add (this.play);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.play]));
		w75.Position = 1;
		w75.Expand = false;
		w75.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.pause = new global::Gtk.Button ();
		this.pause.WidthRequest = 80;
		this.pause.CanFocus = true;
		this.pause.Name = "pause";
		this.pause.UseUnderline = true;
		this.pause.Label = global::Mono.Unix.Catalog.GetString ("Pauza");
		global::Gtk.Image w76 = new global::Gtk.Image ();
		w76.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-pause", global::Gtk.IconSize.Button);
		this.pause.Image = w76;
		this.hbox17.Add (this.pause);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.pause]));
		w77.Position = 2;
		w77.Expand = false;
		w77.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.stop = new global::Gtk.Button ();
		this.stop.WidthRequest = 80;
		this.stop.CanFocus = true;
		this.stop.Name = "stop";
		this.stop.UseUnderline = true;
		this.stop.Label = global::Mono.Unix.Catalog.GetString ("Stop");
		global::Gtk.Image w78 = new global::Gtk.Image ();
		w78.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-stop", global::Gtk.IconSize.Button);
		this.stop.Image = w78;
		this.hbox17.Add (this.stop);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.stop]));
		w79.Position = 3;
		w79.Expand = false;
		w79.Fill = false;
		// Container child hbox17.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox17.Add (this.fixed1);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.fixed1]));
		w80.Position = 4;
		this.vbox2.Add (this.hbox17);
		global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox17]));
		w81.PackType = ((global::Gtk.PackType)(1));
		w81.Position = 5;
		w81.Expand = false;
		w81.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator4 = new global::Gtk.HSeparator ();
		this.hseparator4.Name = "hseparator4";
		this.vbox2.Add (this.hseparator4);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator4]));
		w82.PackType = ((global::Gtk.PackType)(1));
		w82.Position = 6;
		w82.Expand = false;
		w82.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.menu = new global::Gtk.Button ();
		this.menu.WidthRequest = 70;
		this.menu.CanFocus = true;
		this.menu.Name = "menu";
		this.menu.UseUnderline = true;
		this.menu.Label = global::Mono.Unix.Catalog.GetString ("Menu");
		global::Gtk.Image w83 = new global::Gtk.Image ();
		w83.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Button);
		this.menu.Image = w83;
		this.hbox11.Add (this.menu);
		global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.menu]));
		w84.Position = 0;
		w84.Expand = false;
		w84.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.ratio = new global::Gtk.Button ();
		this.ratio.CanFocus = true;
		this.ratio.Name = "ratio";
		this.ratio.UseUnderline = true;
		this.ratio.Label = global::Mono.Unix.Catalog.GetString ("Poměr obrazu");
		this.hbox11.Add (this.ratio);
		global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.ratio]));
		w85.Position = 1;
		w85.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.exit = new global::Gtk.Button ();
		this.exit.WidthRequest = 70;
		this.exit.CanFocus = true;
		this.exit.Name = "exit";
		this.exit.UseUnderline = true;
		this.exit.Label = global::Mono.Unix.Catalog.GetString ("Exit");
		global::Gtk.Image w86 = new global::Gtk.Image ();
		w86.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Button);
		this.exit.Image = w86;
		this.hbox11.Add (this.exit);
		global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.exit]));
		w87.Position = 2;
		w87.Expand = false;
		w87.Fill = false;
		this.vbox2.Add (this.hbox11);
		global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox11]));
		w88.PackType = ((global::Gtk.PackType)(1));
		w88.Position = 7;
		w88.Expand = false;
		w88.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(5)), false);
		this.table1.Name = "table1";
		// Container child table1.Gtk.Table+TableChild
		this.down = new global::Gtk.Button ();
		this.down.CanFocus = true;
		this.down.Name = "down";
		this.down.UseUnderline = true;
		global::Gtk.Image w89 = new global::Gtk.Image ();
		w89.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_down", global::Gtk.IconSize.Menu);
		this.down.Image = w89;
		this.table1.Add (this.down);
		global::Gtk.Table.TableChild w90 = ((global::Gtk.Table.TableChild)(this.table1 [this.down]));
		w90.TopAttach = ((uint)(2));
		w90.BottomAttach = ((uint)(3));
		w90.LeftAttach = ((uint)(2));
		w90.RightAttach = ((uint)(3));
		w90.XOptions = ((global::Gtk.AttachOptions)(4));
		w90.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.fixed20 = new global::Gtk.Fixed ();
		this.fixed20.Name = "fixed20";
		this.fixed20.HasWindow = false;
		this.table1.Add (this.fixed20);
		global::Gtk.Table.TableChild w91 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed20]));
		w91.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.fixed21 = new global::Gtk.Fixed ();
		this.fixed21.Name = "fixed21";
		this.fixed21.HasWindow = false;
		this.table1.Add (this.fixed21);
		global::Gtk.Table.TableChild w92 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed21]));
		w92.LeftAttach = ((uint)(4));
		w92.RightAttach = ((uint)(5));
		w92.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.fixed22 = new global::Gtk.Fixed ();
		this.fixed22.Name = "fixed22";
		this.fixed22.HasWindow = false;
		this.table1.Add (this.fixed22);
		global::Gtk.Table.TableChild w93 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed22]));
		w93.TopAttach = ((uint)(1));
		w93.BottomAttach = ((uint)(2));
		w93.LeftAttach = ((uint)(4));
		w93.RightAttach = ((uint)(5));
		w93.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.fixed23 = new global::Gtk.Fixed ();
		this.fixed23.Name = "fixed23";
		this.fixed23.HasWindow = false;
		this.table1.Add (this.fixed23);
		global::Gtk.Table.TableChild w94 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed23]));
		w94.TopAttach = ((uint)(2));
		w94.BottomAttach = ((uint)(3));
		w94.LeftAttach = ((uint)(4));
		w94.RightAttach = ((uint)(5));
		w94.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.fixed24 = new global::Gtk.Fixed ();
		this.fixed24.Name = "fixed24";
		this.fixed24.HasWindow = false;
		this.table1.Add (this.fixed24);
		global::Gtk.Table.TableChild w95 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed24]));
		w95.TopAttach = ((uint)(1));
		w95.BottomAttach = ((uint)(2));
		w95.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.fixed25 = new global::Gtk.Fixed ();
		this.fixed25.Name = "fixed25";
		this.fixed25.HasWindow = false;
		this.table1.Add (this.fixed25);
		global::Gtk.Table.TableChild w96 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed25]));
		w96.TopAttach = ((uint)(2));
		w96.BottomAttach = ((uint)(3));
		w96.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.fixed26 = new global::Gtk.Fixed ();
		this.fixed26.Name = "fixed26";
		this.fixed26.HasWindow = false;
		this.table1.Add (this.fixed26);
		global::Gtk.Table.TableChild w97 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed26]));
		w97.LeftAttach = ((uint)(1));
		w97.RightAttach = ((uint)(2));
		w97.XOptions = ((global::Gtk.AttachOptions)(4));
		w97.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.fixed27 = new global::Gtk.Fixed ();
		this.fixed27.Name = "fixed27";
		this.fixed27.HasWindow = false;
		this.table1.Add (this.fixed27);
		global::Gtk.Table.TableChild w98 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed27]));
		w98.LeftAttach = ((uint)(3));
		w98.RightAttach = ((uint)(4));
		w98.XOptions = ((global::Gtk.AttachOptions)(4));
		w98.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.fixed29 = new global::Gtk.Fixed ();
		this.fixed29.Name = "fixed29";
		this.fixed29.HasWindow = false;
		this.table1.Add (this.fixed29);
		global::Gtk.Table.TableChild w99 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed29]));
		w99.TopAttach = ((uint)(2));
		w99.BottomAttach = ((uint)(3));
		w99.LeftAttach = ((uint)(1));
		w99.RightAttach = ((uint)(2));
		w99.XOptions = ((global::Gtk.AttachOptions)(4));
		w99.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.fixed30 = new global::Gtk.Fixed ();
		this.fixed30.Name = "fixed30";
		this.fixed30.HasWindow = false;
		this.table1.Add (this.fixed30);
		global::Gtk.Table.TableChild w100 = ((global::Gtk.Table.TableChild)(this.table1 [this.fixed30]));
		w100.TopAttach = ((uint)(2));
		w100.BottomAttach = ((uint)(3));
		w100.LeftAttach = ((uint)(3));
		w100.RightAttach = ((uint)(4));
		w100.XOptions = ((global::Gtk.AttachOptions)(4));
		w100.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.left = new global::Gtk.Button ();
		this.left.CanFocus = true;
		this.left.Name = "left";
		this.left.UseUnderline = true;
		global::Gtk.Image w101 = new global::Gtk.Image ();
		w101.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_left", global::Gtk.IconSize.Menu);
		this.left.Image = w101;
		this.table1.Add (this.left);
		global::Gtk.Table.TableChild w102 = ((global::Gtk.Table.TableChild)(this.table1 [this.left]));
		w102.TopAttach = ((uint)(1));
		w102.BottomAttach = ((uint)(2));
		w102.LeftAttach = ((uint)(1));
		w102.RightAttach = ((uint)(2));
		w102.XOptions = ((global::Gtk.AttachOptions)(4));
		w102.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.ok = new global::Gtk.Button ();
		this.ok.CanFocus = true;
		this.ok.Name = "ok";
		this.ok.UseUnderline = true;
		global::Gtk.Image w103 = new global::Gtk.Image ();
		w103.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Button);
		this.ok.Image = w103;
		this.table1.Add (this.ok);
		global::Gtk.Table.TableChild w104 = ((global::Gtk.Table.TableChild)(this.table1 [this.ok]));
		w104.TopAttach = ((uint)(1));
		w104.BottomAttach = ((uint)(2));
		w104.LeftAttach = ((uint)(2));
		w104.RightAttach = ((uint)(3));
		w104.XOptions = ((global::Gtk.AttachOptions)(4));
		w104.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.right = new global::Gtk.Button ();
		this.right.CanFocus = true;
		this.right.Name = "right";
		this.right.UseUnderline = true;
		global::Gtk.Image w105 = new global::Gtk.Image ();
		w105.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_right", global::Gtk.IconSize.Menu);
		this.right.Image = w105;
		this.table1.Add (this.right);
		global::Gtk.Table.TableChild w106 = ((global::Gtk.Table.TableChild)(this.table1 [this.right]));
		w106.TopAttach = ((uint)(1));
		w106.BottomAttach = ((uint)(2));
		w106.LeftAttach = ((uint)(3));
		w106.RightAttach = ((uint)(4));
		w106.XOptions = ((global::Gtk.AttachOptions)(4));
		w106.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.up = new global::Gtk.Button ();
		this.up.CanFocus = true;
		this.up.Name = "up";
		this.up.UseUnderline = true;
		global::Gtk.Image w107 = new global::Gtk.Image ();
		w107.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_up", global::Gtk.IconSize.Menu);
		this.up.Image = w107;
		this.table1.Add (this.up);
		global::Gtk.Table.TableChild w108 = ((global::Gtk.Table.TableChild)(this.table1 [this.up]));
		w108.LeftAttach = ((uint)(2));
		w108.RightAttach = ((uint)(3));
		w108.XOptions = ((global::Gtk.AttachOptions)(4));
		w108.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox2.Add (this.table1);
		global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
		w109.PackType = ((global::Gtk.PackType)(1));
		w109.Position = 8;
		w109.Expand = false;
		w109.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator ();
		this.hseparator2.Name = "hseparator2";
		this.vbox2.Add (this.hseparator2);
		global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator2]));
		w110.PackType = ((global::Gtk.PackType)(1));
		w110.Position = 9;
		w110.Expand = false;
		w110.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.fixed17 = new global::Gtk.Fixed ();
		this.fixed17.Name = "fixed17";
		this.fixed17.HasWindow = false;
		this.hbox9.Add (this.fixed17);
		global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.fixed17]));
		w111.Position = 0;
		// Container child hbox9.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.vup = new global::Gtk.Button ();
		this.vup.CanFocus = true;
		this.vup.Name = "vup";
		this.vup.UseUnderline = true;
		global::Gtk.Image w112 = new global::Gtk.Image ();
		w112.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_up", global::Gtk.IconSize.Menu);
		this.vup.Image = w112;
		this.vbox7.Add (this.vup);
		global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.vup]));
		w113.Position = 0;
		w113.Expand = false;
		w113.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.image31 = new global::Gtk.Image ();
		this.image31.Name = "image31";
		this.image31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_volume", global::Gtk.IconSize.Button);
		this.vbox7.Add (this.image31);
		global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.image31]));
		w114.Position = 1;
		w114.Expand = false;
		w114.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.vdown = new global::Gtk.Button ();
		this.vdown.CanFocus = true;
		this.vdown.Name = "vdown";
		this.vdown.UseUnderline = true;
		global::Gtk.Image w115 = new global::Gtk.Image ();
		w115.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_down", global::Gtk.IconSize.Menu);
		this.vdown.Image = w115;
		this.vbox7.Add (this.vdown);
		global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.vdown]));
		w116.PackType = ((global::Gtk.PackType)(1));
		w116.Position = 2;
		w116.Expand = false;
		w116.Fill = false;
		this.hbox9.Add (this.vbox7);
		global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox7]));
		w117.Position = 1;
		w117.Expand = false;
		w117.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.fixed18 = new global::Gtk.Fixed ();
		this.fixed18.HeightRequest = 23;
		this.fixed18.Name = "fixed18";
		this.fixed18.HasWindow = false;
		this.vbox8.Add (this.fixed18);
		global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.fixed18]));
		w118.Position = 0;
		w118.Expand = false;
		w118.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.mute = new global::Gtk.Button ();
		this.mute.CanFocus = true;
		this.mute.Name = "mute";
		this.mute.UseUnderline = true;
		global::Gtk.Image w119 = new global::Gtk.Image ();
		w119.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_volume", global::Gtk.IconSize.Button);
		this.mute.Image = w119;
		this.vbox8.Add (this.mute);
		global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.mute]));
		w120.Position = 1;
		w120.Expand = false;
		w120.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.fixed19 = new global::Gtk.Fixed ();
		this.fixed19.Name = "fixed19";
		this.fixed19.HasWindow = false;
		this.vbox8.Add (this.fixed19);
		global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.fixed19]));
		w121.Position = 2;
		w121.Expand = false;
		w121.Fill = false;
		this.hbox9.Add (this.vbox8);
		global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox8]));
		w122.Position = 2;
		w122.Expand = false;
		w122.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.pup = new global::Gtk.Button ();
		this.pup.CanFocus = true;
		this.pup.Name = "pup";
		this.pup.UseUnderline = true;
		global::Gtk.Image w123 = new global::Gtk.Image ();
		w123.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_up", global::Gtk.IconSize.Menu);
		this.pup.Image = w123;
		this.vbox6.Add (this.pup);
		global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.pup]));
		w124.Position = 0;
		w124.Expand = false;
		w124.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.image37 = new global::Gtk.Image ();
		this.image37.Name = "image37";
		this.image37.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dnd-multiple", global::Gtk.IconSize.Menu);
		this.vbox6.Add (this.image37);
		global::Gtk.Box.BoxChild w125 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.image37]));
		w125.Position = 1;
		w125.Expand = false;
		w125.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.pdown = new global::Gtk.Button ();
		this.pdown.CanFocus = true;
		this.pdown.Name = "pdown";
		this.pdown.UseUnderline = true;
		global::Gtk.Image w126 = new global::Gtk.Image ();
		w126.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_down", global::Gtk.IconSize.Menu);
		this.pdown.Image = w126;
		this.vbox6.Add (this.pdown);
		global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.pdown]));
		w127.PackType = ((global::Gtk.PackType)(1));
		w127.Position = 2;
		w127.Expand = false;
		w127.Fill = false;
		this.hbox9.Add (this.vbox6);
		global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox6]));
		w128.Position = 3;
		w128.Expand = false;
		w128.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.fixed16 = new global::Gtk.Fixed ();
		this.fixed16.Name = "fixed16";
		this.fixed16.HasWindow = false;
		this.hbox9.Add (this.fixed16);
		global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.fixed16]));
		w129.Position = 4;
		this.vbox2.Add (this.hbox9);
		global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox9]));
		w130.PackType = ((global::Gtk.PackType)(1));
		w130.Position = 10;
		w130.Expand = false;
		w130.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator5 = new global::Gtk.HSeparator ();
		this.hseparator5.Name = "hseparator5";
		this.vbox2.Add (this.hseparator5);
		global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator5]));
		w131.PackType = ((global::Gtk.PackType)(1));
		w131.Position = 11;
		w131.Expand = false;
		w131.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 3;
		// Container child hbox10.Gtk.Box+BoxChild
		this.fixed8 = new global::Gtk.Fixed ();
		this.fixed8.Name = "fixed8";
		this.fixed8.HasWindow = false;
		this.hbox10.Add (this.fixed8);
		global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.fixed8]));
		w132.Position = 0;
		// Container child hbox10.Gtk.Box+BoxChild
		this.list = new global::Gtk.Button ();
		this.list.WidthRequest = 64;
		this.list.CanFocus = true;
		this.list.Name = "list";
		this.list.UseUnderline = true;
		this.list.Label = global::Mono.Unix.Catalog.GetString ("List");
		global::Gtk.Image w133 = new global::Gtk.Image ();
		w133.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-index", global::Gtk.IconSize.Button);
		this.list.Image = w133;
		this.hbox10.Add (this.list);
		global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.list]));
		w134.Position = 1;
		w134.Expand = false;
		w134.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.n = new global::Gtk.Button ();
		this.n.WidthRequest = 30;
		this.n.HeightRequest = 30;
		this.n.CanFocus = true;
		this.n.Name = "n";
		this.n.UseUnderline = true;
		this.n.Label = global::Mono.Unix.Catalog.GetString ("0");
		this.hbox10.Add (this.n);
		global::Gtk.Box.BoxChild w135 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.n]));
		w135.Position = 2;
		w135.Expand = false;
		w135.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.qview = new global::Gtk.Button ();
		this.qview.WidthRequest = 64;
		this.qview.CanFocus = true;
		this.qview.Name = "qview";
		this.qview.UseUnderline = true;
		this.qview.Label = global::Mono.Unix.Catalog.GetString ("Zpět");
		global::Gtk.Image w136 = new global::Gtk.Image ();
		w136.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-jump-to", global::Gtk.IconSize.Button);
		this.qview.Image = w136;
		this.hbox10.Add (this.qview);
		global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.qview]));
		w137.Position = 3;
		w137.Expand = false;
		w137.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.fixed15 = new global::Gtk.Fixed ();
		this.fixed15.Name = "fixed15";
		this.fixed15.HasWindow = false;
		this.hbox10.Add (this.fixed15);
		global::Gtk.Box.BoxChild w138 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.fixed15]));
		w138.Position = 4;
		this.vbox2.Add (this.hbox10);
		global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox10]));
		w139.PackType = ((global::Gtk.PackType)(1));
		w139.Position = 12;
		w139.Expand = false;
		w139.Fill = false;
		this.GtkAlignment24.Add (this.vbox2);
		this.frame2.Add (this.GtkAlignment24);
		this.GtkLabel46 = new global::Gtk.Label ();
		this.GtkLabel46.Name = "GtkLabel46";
		this.GtkLabel46.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Ovladač</b>");
		this.GtkLabel46.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel46;
		this.vbox10.Add (this.frame2);
		global::Gtk.Box.BoxChild w142 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.frame2]));
		w142.Position = 1;
		w142.Expand = false;
		w142.Fill = false;
		this.hbox7.Add (this.vbox10);
		global::Gtk.Box.BoxChild w143 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vbox10]));
		w143.Position = 0;
		w143.Expand = false;
		w143.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator ();
		this.vseparator1.Name = "vseparator1";
		this.hbox7.Add (this.vseparator1);
		global::Gtk.Box.BoxChild w144 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vseparator1]));
		w144.Position = 1;
		w144.Expand = false;
		w144.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Stav TV:</b>");
		this.label1.UseMarkup = true;
		this.hbox2.Add (this.label1);
		global::Gtk.Box.BoxChild w145 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
		w145.Position = 0;
		w145.Expand = false;
		w145.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.tvstate = new global::Gtk.Label ();
		this.tvstate.Name = "tvstate";
		this.tvstate.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Neznámý</i>");
		this.tvstate.UseMarkup = true;
		this.hbox2.Add (this.tvstate);
		global::Gtk.Box.BoxChild w146 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.tvstate]));
		w146.Position = 1;
		w146.Expand = false;
		w146.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.tvimage = new global::Gtk.Image ();
		this.tvimage.Name = "tvimage";
		this.tvimage.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.LargeToolbar);
		this.hbox2.Add (this.tvimage);
		global::Gtk.Box.BoxChild w147 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.tvimage]));
		w147.Position = 2;
		w147.Expand = false;
		w147.Fill = false;
		this.vbox9.Add (this.hbox2);
		global::Gtk.Box.BoxChild w148 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox2]));
		w148.Position = 0;
		w148.Expand = false;
		w148.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox9.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w149 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hseparator1]));
		w149.Position = 1;
		w149.Expand = false;
		w149.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Poměr obrazu:</b>");
		this.label4.UseMarkup = true;
		this.hbox4.Add (this.label4);
		global::Gtk.Box.BoxChild w150 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label4]));
		w150.Position = 0;
		w150.Expand = false;
		w150.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.aspect = new global::Gtk.Label ();
		this.aspect.Name = "aspect";
		this.aspect.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Neznámý</i>");
		this.aspect.UseMarkup = true;
		this.hbox4.Add (this.aspect);
		global::Gtk.Box.BoxChild w151 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.aspect]));
		w151.Position = 1;
		w151.Expand = false;
		w151.Fill = false;
		this.vbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w152 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
		w152.Position = 0;
		w152.Expand = false;
		w152.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.aspectselect = global::Gtk.ComboBox.NewText ();
		this.aspectselect.AppendText (global::Mono.Unix.Catalog.GetString ("16:9"));
		this.aspectselect.AppendText (global::Mono.Unix.Catalog.GetString ("4:3"));
		this.aspectselect.AppendText (global::Mono.Unix.Catalog.GetString ("14:9"));
		this.aspectselect.AppendText (global::Mono.Unix.Catalog.GetString ("Přiblížený"));
		this.aspectselect.AppendText (global::Mono.Unix.Catalog.GetString ("Originál"));
		this.aspectselect.AppendText (global::Mono.Unix.Catalog.GetString ("Jen skenovat"));
		this.aspectselect.AppendText (global::Mono.Unix.Catalog.GetString ("Plná šířka"));
		this.aspectselect.AppendText (global::Mono.Unix.Catalog.GetString ("Cinema Zoom 1"));
		this.aspectselect.Name = "aspectselect";
		this.aspectselect.Active = 0;
		this.hbox3.Add (this.aspectselect);
		global::Gtk.Box.BoxChild w153 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.aspectselect]));
		w153.Position = 0;
		w153.Expand = false;
		w153.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.aspectsend = new global::Gtk.Button ();
		this.aspectsend.CanFocus = true;
		this.aspectsend.Name = "aspectsend";
		this.aspectsend.UseUnderline = true;
		this.aspectsend.Label = global::Mono.Unix.Catalog.GetString ("OK");
		global::Gtk.Image w154 = new global::Gtk.Image ();
		w154.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Button);
		this.aspectsend.Image = w154;
		this.hbox3.Add (this.aspectsend);
		global::Gtk.Box.BoxChild w155 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.aspectsend]));
		w155.Position = 1;
		w155.Expand = false;
		w155.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w156 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w156.Position = 1;
		w156.Expand = false;
		w156.Fill = false;
		this.vbox9.Add (this.vbox1);
		global::Gtk.Box.BoxChild w157 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox1]));
		w157.Position = 2;
		w157.Expand = false;
		w157.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hseparator6 = new global::Gtk.HSeparator ();
		this.hseparator6.Name = "hseparator6";
		this.vbox9.Add (this.hseparator6);
		global::Gtk.Box.BoxChild w158 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hseparator6]));
		w158.Position = 3;
		w158.Expand = false;
		w158.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox ();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Hlasitost:</b>");
		this.label5.UseMarkup = true;
		this.hbox6.Add (this.label5);
		global::Gtk.Box.BoxChild w159 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label5]));
		w159.Position = 0;
		w159.Expand = false;
		w159.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.volumeview = new global::Gtk.Label ();
		this.volumeview.Name = "volumeview";
		this.volumeview.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Neznámá</i>");
		this.volumeview.UseMarkup = true;
		this.hbox6.Add (this.volumeview);
		global::Gtk.Box.BoxChild w160 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.volumeview]));
		w160.Position = 1;
		w160.Expand = false;
		w160.Fill = false;
		this.vbox11.Add (this.hbox6);
		global::Gtk.Box.BoxChild w161 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox6]));
		w161.Position = 0;
		w161.Expand = false;
		w161.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.hbox5.Add (this.fixed2);
		global::Gtk.Box.BoxChild w162 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed2]));
		w162.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.volumeselect = new global::Gtk.SpinButton (0, 20, 1);
		this.volumeselect.CanFocus = true;
		this.volumeselect.Name = "volumeselect";
		this.volumeselect.Adjustment.PageIncrement = 5;
		this.volumeselect.ClimbRate = 1;
		this.volumeselect.Numeric = true;
		this.volumeselect.Value = 6;
		this.hbox5.Add (this.volumeselect);
		global::Gtk.Box.BoxChild w163 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.volumeselect]));
		w163.Position = 1;
		w163.Expand = false;
		w163.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.volumesend = new global::Gtk.Button ();
		this.volumesend.CanFocus = true;
		this.volumesend.Name = "volumesend";
		this.volumesend.UseUnderline = true;
		this.volumesend.Label = global::Mono.Unix.Catalog.GetString ("OK");
		global::Gtk.Image w164 = new global::Gtk.Image ();
		w164.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Button);
		this.volumesend.Image = w164;
		this.hbox5.Add (this.volumesend);
		global::Gtk.Box.BoxChild w165 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.volumesend]));
		w165.Position = 2;
		w165.Expand = false;
		w165.Fill = false;
		this.vbox11.Add (this.hbox5);
		global::Gtk.Box.BoxChild w166 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox5]));
		w166.Position = 1;
		w166.Expand = false;
		w166.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.volumescroll = new global::Gtk.HScale (null);
		this.volumescroll.CanFocus = true;
		this.volumescroll.Name = "volumescroll";
		this.volumescroll.Adjustment.Upper = 20;
		this.volumescroll.Adjustment.PageIncrement = 5;
		this.volumescroll.Adjustment.StepIncrement = 1;
		this.volumescroll.Adjustment.Value = 6;
		this.volumescroll.DrawValue = true;
		this.volumescroll.Digits = 0;
		this.volumescroll.ValuePos = ((global::Gtk.PositionType)(2));
		this.vbox11.Add (this.volumescroll);
		global::Gtk.Box.BoxChild w167 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.volumescroll]));
		w167.PackType = ((global::Gtk.PackType)(1));
		w167.Position = 2;
		w167.Expand = false;
		w167.Fill = false;
		this.vbox9.Add (this.vbox11);
		global::Gtk.Box.BoxChild w168 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox11]));
		w168.Position = 4;
		w168.Expand = false;
		w168.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hseparator7 = new global::Gtk.HSeparator ();
		this.hseparator7.Name = "hseparator7";
		this.vbox9.Add (this.hseparator7);
		global::Gtk.Box.BoxChild w169 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hseparator7]));
		w169.Position = 5;
		w169.Expand = false;
		w169.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.vbox12 = new global::Gtk.VBox ();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox ();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Program:</b>");
		this.label6.UseMarkup = true;
		this.hbox14.Add (this.label6);
		global::Gtk.Box.BoxChild w170 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label6]));
		w170.Position = 0;
		w170.Expand = false;
		w170.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.programview = new global::Gtk.Label ();
		this.programview.Name = "programview";
		this.programview.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Neznámý</i>");
		this.programview.UseMarkup = true;
		this.hbox14.Add (this.programview);
		global::Gtk.Box.BoxChild w171 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.programview]));
		w171.Position = 1;
		w171.Expand = false;
		w171.Fill = false;
		this.vbox12.Add (this.hbox14);
		global::Gtk.Box.BoxChild w172 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox14]));
		w172.Position = 0;
		w172.Expand = false;
		w172.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.hbox8.Add (this.fixed3);
		global::Gtk.Box.BoxChild w173 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.fixed3]));
		w173.Position = 0;
		// Container child hbox8.Gtk.Box+BoxChild
		this.programselect = new global::Gtk.SpinButton (0, 255, 1);
		this.programselect.CanFocus = true;
		this.programselect.Name = "programselect";
		this.programselect.Adjustment.PageIncrement = 10;
		this.programselect.ClimbRate = 1;
		this.programselect.Numeric = true;
		this.hbox8.Add (this.programselect);
		global::Gtk.Box.BoxChild w174 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.programselect]));
		w174.Position = 1;
		w174.Expand = false;
		w174.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.programbut = new global::Gtk.Button ();
		this.programbut.CanFocus = true;
		this.programbut.Name = "programbut";
		this.programbut.UseUnderline = true;
		this.programbut.Label = global::Mono.Unix.Catalog.GetString ("OK");
		global::Gtk.Image w175 = new global::Gtk.Image ();
		w175.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Button);
		this.programbut.Image = w175;
		this.hbox8.Add (this.programbut);
		global::Gtk.Box.BoxChild w176 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.programbut]));
		w176.Position = 2;
		w176.Expand = false;
		w176.Fill = false;
		this.vbox12.Add (this.hbox8);
		global::Gtk.Box.BoxChild w177 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox8]));
		w177.Position = 1;
		w177.Expand = false;
		w177.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Pozn.: Pouze čísla kanálů</i>");
		this.label2.UseMarkup = true;
		this.vbox12.Add (this.label2);
		global::Gtk.Box.BoxChild w178 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.label2]));
		w178.PackType = ((global::Gtk.PackType)(1));
		w178.Position = 2;
		w178.Expand = false;
		w178.Fill = false;
		this.vbox9.Add (this.vbox12);
		global::Gtk.Box.BoxChild w179 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox12]));
		w179.Position = 6;
		w179.Expand = false;
		w179.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hseparator8 = new global::Gtk.HSeparator ();
		this.hseparator8.Name = "hseparator8";
		this.vbox9.Add (this.hseparator8);
		global::Gtk.Box.BoxChild w180 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hseparator8]));
		w180.Position = 7;
		w180.Expand = false;
		w180.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox15 = new global::Gtk.HBox ();
		this.hbox15.Name = "hbox15";
		this.hbox15.Spacing = 6;
		// Container child hbox15.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Vstup:</b>");
		this.label7.UseMarkup = true;
		this.hbox15.Add (this.label7);
		global::Gtk.Box.BoxChild w181 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label7]));
		w181.Position = 0;
		w181.Expand = false;
		w181.Fill = false;
		// Container child hbox15.Gtk.Box+BoxChild
		this.inputview = new global::Gtk.Label ();
		this.inputview.Name = "inputview";
		this.inputview.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Neznámý</i>");
		this.inputview.UseMarkup = true;
		this.hbox15.Add (this.inputview);
		global::Gtk.Box.BoxChild w182 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.inputview]));
		w182.Position = 1;
		w182.Expand = false;
		w182.Fill = false;
		this.vbox5.Add (this.hbox15);
		global::Gtk.Box.BoxChild w183 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox15]));
		w183.Position = 0;
		w183.Expand = false;
		w183.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox16 = new global::Gtk.HBox ();
		this.hbox16.Name = "hbox16";
		this.hbox16.Spacing = 6;
		// Container child hbox16.Gtk.Box+BoxChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		this.hbox16.Add (this.fixed4);
		global::Gtk.Box.BoxChild w184 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.fixed4]));
		w184.Position = 0;
		// Container child hbox16.Gtk.Box+BoxChild
		this.inputselect = global::Gtk.ComboBox.NewText ();
		this.inputselect.AppendText (global::Mono.Unix.Catalog.GetString ("DTV"));
		this.inputselect.AppendText (global::Mono.Unix.Catalog.GetString ("AV1"));
		this.inputselect.AppendText (global::Mono.Unix.Catalog.GetString ("AV2"));
		this.inputselect.AppendText (global::Mono.Unix.Catalog.GetString ("HDMI"));
		this.inputselect.AppendText (global::Mono.Unix.Catalog.GetString ("RGB"));
		this.inputselect.AppendText (global::Mono.Unix.Catalog.GetString ("Komponentní"));
		this.inputselect.Name = "inputselect";
		this.inputselect.Active = 0;
		this.hbox16.Add (this.inputselect);
		global::Gtk.Box.BoxChild w185 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.inputselect]));
		w185.Position = 1;
		w185.Expand = false;
		w185.Fill = false;
		// Container child hbox16.Gtk.Box+BoxChild
		this.inputsend = new global::Gtk.Button ();
		this.inputsend.CanFocus = true;
		this.inputsend.Name = "inputsend";
		this.inputsend.UseUnderline = true;
		this.inputsend.Label = global::Mono.Unix.Catalog.GetString ("OK");
		global::Gtk.Image w186 = new global::Gtk.Image ();
		w186.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Button);
		this.inputsend.Image = w186;
		this.hbox16.Add (this.inputsend);
		global::Gtk.Box.BoxChild w187 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.inputsend]));
		w187.Position = 2;
		w187.Expand = false;
		w187.Fill = false;
		this.vbox5.Add (this.hbox16);
		global::Gtk.Box.BoxChild w188 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox16]));
		w188.Position = 1;
		w188.Expand = false;
		w188.Fill = false;
		this.vbox9.Add (this.vbox5);
		global::Gtk.Box.BoxChild w189 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox5]));
		w189.Position = 8;
		w189.Expand = false;
		w189.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.autoconf = new global::Gtk.Button ();
		this.autoconf.Sensitive = false;
		this.autoconf.CanFocus = true;
		this.autoconf.Name = "autoconf";
		this.autoconf.UseUnderline = true;
		this.autoconf.Label = global::Mono.Unix.Catalog.GetString ("Autokonfigurace obrazu");
		global::Gtk.Image w190 = new global::Gtk.Image ();
		w190.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_properties", global::Gtk.IconSize.Button);
		this.autoconf.Image = w190;
		this.vbox9.Add (this.autoconf);
		global::Gtk.Box.BoxChild w191 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.autoconf]));
		w191.Position = 9;
		w191.Expand = false;
		w191.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hseparator9 = new global::Gtk.HSeparator ();
		this.hseparator9.Name = "hseparator9";
		this.vbox9.Add (this.hseparator9);
		global::Gtk.Box.BoxChild w192 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hseparator9]));
		w192.Position = 10;
		w192.Expand = false;
		w192.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.vbox13 = new global::Gtk.VBox ();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.quit = new global::Gtk.Button ();
		this.quit.CanFocus = true;
		this.quit.Name = "quit";
		this.quit.UseStock = true;
		this.quit.UseUnderline = true;
		this.quit.Label = "gtk-quit";
		this.vbox13.Add (this.quit);
		global::Gtk.Box.BoxChild w193 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.quit]));
		w193.PackType = ((global::Gtk.PackType)(1));
		w193.Position = 1;
		w193.Expand = false;
		w193.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("O programu");
		this.vbox13.Add (this.button3);
		global::Gtk.Box.BoxChild w194 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.button3]));
		w194.PackType = ((global::Gtk.PackType)(1));
		w194.Position = 2;
		w194.Expand = false;
		w194.Fill = false;
		this.vbox9.Add (this.vbox13);
		global::Gtk.Box.BoxChild w195 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox13]));
		w195.Position = 11;
		this.hbox7.Add (this.vbox9);
		global::Gtk.Box.BoxChild w196 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vbox9]));
		w196.Position = 2;
		w196.Expand = false;
		w196.Fill = false;
		this.Add (this.hbox7);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 602;
		this.DefaultHeight = 705;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button51.Clicked += new global::System.EventHandler (this.inith);
		this.tvrad.Clicked += new global::System.EventHandler (this.handleKey);
		this.avmode.Clicked += new global::System.EventHandler (this.handleKey);
		this.power.Clicked += new global::System.EventHandler (this.handleKey);
		this.input.Clicked += new global::System.EventHandler (this.handleKey);
		this.energysaving.Clicked += new global::System.EventHandler (this.handleKey);
		this.n9.Clicked += new global::System.EventHandler (this.handleKey);
		this.n8.Clicked += new global::System.EventHandler (this.handleKey);
		this.n7.Clicked += new global::System.EventHandler (this.handleKey);
		this.n6.Clicked += new global::System.EventHandler (this.handleKey);
		this.n5.Clicked += new global::System.EventHandler (this.handleKey);
		this.n4.Clicked += new global::System.EventHandler (this.handleKey);
		this.n3.Clicked += new global::System.EventHandler (this.handleKey);
		this.n2.Clicked += new global::System.EventHandler (this.handleKey);
		this.n1.Clicked += new global::System.EventHandler (this.handleKey);
		this.list.Clicked += new global::System.EventHandler (this.handleKey);
		this.n.Clicked += new global::System.EventHandler (this.handleKey);
		this.qview.Clicked += new global::System.EventHandler (this.handleKey);
		this.vup.Clicked += new global::System.EventHandler (this.handleKey);
		this.vdown.Clicked += new global::System.EventHandler (this.handleKey);
		this.mute.Clicked += new global::System.EventHandler (this.handleKey);
		this.pup.Clicked += new global::System.EventHandler (this.handleKey);
		this.pdown.Clicked += new global::System.EventHandler (this.handleKey);
		this.up.Clicked += new global::System.EventHandler (this.handleKey);
		this.right.Clicked += new global::System.EventHandler (this.handleKey);
		this.ok.Clicked += new global::System.EventHandler (this.handleKey);
		this.left.Clicked += new global::System.EventHandler (this.handleKey);
		this.down.Clicked += new global::System.EventHandler (this.handleKey);
		this.menu.Clicked += new global::System.EventHandler (this.handleKey);
		this.ratio.Clicked += new global::System.EventHandler (this.handleKey);
		this.exit.Clicked += new global::System.EventHandler (this.handleKey);
		this.play.Clicked += new global::System.EventHandler (this.handleKey);
		this.pause.Clicked += new global::System.EventHandler (this.handleKey);
		this.stop.Clicked += new global::System.EventHandler (this.handleKey);
		this.bwd.Clicked += new global::System.EventHandler (this.handleKey);
		this.fwd.Clicked += new global::System.EventHandler (this.handleKey);
		this.yellow.Clicked += new global::System.EventHandler (this.handleKey);
		this.topt.Clicked += new global::System.EventHandler (this.handleKey);
		this.text.Clicked += new global::System.EventHandler (this.handleKey);
		this.subtitle.Clicked += new global::System.EventHandler (this.handleKey);
		this.simplink.Clicked += new global::System.EventHandler (this.handleKey);
		this.red.Clicked += new global::System.EventHandler (this.handleKey);
		this.qmenu.Clicked += new global::System.EventHandler (this.handleKey);
		this.markfav.Clicked += new global::System.EventHandler (this.handleKey);
		this.info.Clicked += new global::System.EventHandler (this.handleKey);
		this.green.Clicked += new global::System.EventHandler (this.handleKey);
		this.epg.Clicked += new global::System.EventHandler (this.handleKey);
		this.blue.Clicked += new global::System.EventHandler (this.handleKey);
		this.aspectsend.Clicked += new global::System.EventHandler (this.sendDirect);
		this.volumeselect.Changed += new global::System.EventHandler (this.sendDirect);
		this.volumesend.Clicked += new global::System.EventHandler (this.sendDirect);
		this.volumescroll.ValueChanged += new global::System.EventHandler (this.sendDirect);
		this.programselect.Changed += new global::System.EventHandler (this.sendDirect);
		this.programbut.Clicked += new global::System.EventHandler (this.sendDirect);
		this.inputsend.Clicked += new global::System.EventHandler (this.sendDirect);
		this.autoconf.Clicked += new global::System.EventHandler (this.sendDirect);
		this.button3.Clicked += new global::System.EventHandler (this.abouth);
		this.quit.Clicked += new global::System.EventHandler (this.quith);
	}
}
